'use client';

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Loader2, Check, X, AlertTriangle } from 'lucide-react';
import { useToast } from '@/components/ui/use-toast';
import { MainLayout } from '@/components/layout/main-layout';

export default function AdminEvolutionPage() {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const { data: candidates = [], isLoading } = useQuery({
    queryKey: ['evolutionCandidates'],
    queryFn: () => api.getEvolutionCandidates(),
  });

  const mutation = useMutation({
    mutationFn: ({ id, action }: { id: string; action: 'approve' | 'reject' }) =>
      api.handleEvolutionCandidate(id, action),
    onSuccess: (_, variables) => {
      toast({ title: `Candidate ${variables.action}ed successfully` });
      queryClient.invalidateQueries({ queryKey: ['evolutionCandidates'] });
    },
    onError: () => {
      toast({ title: 'Operation failed', variant: 'destructive' });
    },
  });

  const { data: stats } = useQuery({
    queryKey: ['evolutionStats'],
    queryFn: () => api.getEvolutionStats(),
  });

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-full">
        <Loader2 className="h-8 w-8 animate-spin" />
      </div>
    );
  }

  return (
    <MainLayout>
      <div className="space-y-6 p-6">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">AI Evolution Control</h2>
          <p className="text-muted-foreground">Review and approve self-improvement candidates generated by the system.</p>
        </div>

        <div className="grid gap-4 md:grid-cols-4">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Pending Candidates</CardTitle>
              <AlertTriangle className="h-4 w-4 text-yellow-500" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{stats?.candidates.pending || 0}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Applied Improvements</CardTitle>
              <Check className="h-4 w-4 text-green-500" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{stats?.candidates.applied || 0}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Avg Trust Score (7d)</CardTitle>
              <Badge variant={stats?.trustScore.average > 0.8 ? 'default' : 'secondary'}>
                 {Math.round((stats?.trustScore.average || 0) * 100)}%
              </Badge>
            </CardHeader>
            <CardContent>
               <p className="text-xs text-muted-foreground">{stats?.trustScore.sampleSize || 0} signals analyzed</p>
            </CardContent>
          </Card>
        </div>

        <div className="grid gap-4">
          {candidates.length === 0 ? (
            <p className="text-muted-foreground">No pending evolution candidates.</p>
          ) : (
            candidates.map((candidate: any) => (
              <Card key={candidate.id}>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <CardTitle className="text-lg">
                        {candidate.type === 'METADATA' ? 'Metadata Improvement' : 'Prompt Optimization'}
                      </CardTitle>
                      <Badge variant="outline">{candidate.targetId}</Badge>
                    </div>
                    <div className="text-sm text-muted-foreground">
                      {new Date(candidate.createdAt).toLocaleDateString()}
                    </div>
                  </div>
                  <CardDescription>{candidate.reasoning}</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="bg-muted p-4 rounded-md mb-4 text-sm font-mono">
                    <pre>{JSON.stringify(candidate.proposedChange, null, 2)}</pre>
                  </div>
                  
                  <div className="flex justify-end gap-2">
                    <Button
                      variant="outline"
                      className="gap-1 text-red-500 hover:text-red-600 hover:bg-red-50"
                      onClick={() => mutation.mutate({ id: candidate.id, action: 'reject' })}
                      disabled={mutation.isPending}
                    >
                      <X className="h-4 w-4" />
                      Reject
                    </Button>
                    <Button
                      className="gap-1 bg-green-600 hover:bg-green-700"
                      onClick={() => mutation.mutate({ id: candidate.id, action: 'approve' })}
                      disabled={mutation.isPending}
                    >
                      <Check className="h-4 w-4" />
                      Approve & Apply
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </div>
      </div>
    </MainLayout>
  );
}
