package com.jask.bitbucket.model;

import java.io.Serializable;

/**
 * Represents a single code suggestion generated by AI analysis.
 */
public class CodeSuggestion implements Serializable {
    private static final long serialVersionUID = 1L;

    public enum Severity {
        CRITICAL,  // 즉시 수정 필요 (보안 취약점, 심각한 버그)
        WARNING,   // 수정 권장 (성능 이슈, 잠재적 버그)
        INFO,      // 개선 제안 (코드 스타일, 가독성)
        HINT       // 참고 사항 (Best practice)
    }

    public enum Category {
        SECURITY,       // 보안 관련
        PERFORMANCE,    // 성능 최적화
        BUG_RISK,       // 버그 위험
        CODE_STYLE,     // 코드 스타일
        BEST_PRACTICE,  // 모범 사례
        DUPLICATION,    // 중복 코드
        COMPLEXITY,     // 복잡도
        ERROR_HANDLING  // 에러 처리
    }

    private long id;
    private long pullRequestId;
    private int repositoryId;
    private String filePath;
    private int startLine;
    private int endLine;
    private String originalCode;
    private String suggestedCode;
    private String explanation;
    private Severity severity;
    private Category category;
    private double confidence;
    private String status; // PENDING, ACCEPTED, REJECTED, DISMISSED
    private String createdAt;
    private String resolvedBy;

    public CodeSuggestion() {}

    // Getters and Setters
    public long getId() { return id; }
    public void setId(long id) { this.id = id; }

    public long getPullRequestId() { return pullRequestId; }
    public void setPullRequestId(long pullRequestId) { this.pullRequestId = pullRequestId; }

    public int getRepositoryId() { return repositoryId; }
    public void setRepositoryId(int repositoryId) { this.repositoryId = repositoryId; }

    public String getFilePath() { return filePath; }
    public void setFilePath(String filePath) { this.filePath = filePath; }

    public int getStartLine() { return startLine; }
    public void setStartLine(int startLine) { this.startLine = startLine; }

    public int getEndLine() { return endLine; }
    public void setEndLine(int endLine) { this.endLine = endLine; }

    public String getOriginalCode() { return originalCode; }
    public void setOriginalCode(String originalCode) { this.originalCode = originalCode; }

    public String getSuggestedCode() { return suggestedCode; }
    public void setSuggestedCode(String suggestedCode) { this.suggestedCode = suggestedCode; }

    public String getExplanation() { return explanation; }
    public void setExplanation(String explanation) { this.explanation = explanation; }

    public Severity getSeverity() { return severity; }
    public void setSeverity(Severity severity) { this.severity = severity; }

    public Category getCategory() { return category; }
    public void setCategory(Category category) { this.category = category; }

    public double getConfidence() { return confidence; }
    public void setConfidence(double confidence) { this.confidence = confidence; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public String getCreatedAt() { return createdAt; }
    public void setCreatedAt(String createdAt) { this.createdAt = createdAt; }

    public String getResolvedBy() { return resolvedBy; }
    public void setResolvedBy(String resolvedBy) { this.resolvedBy = resolvedBy; }
}
